name: Build and Deploy TreeTrack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (for Java-based Android project)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Build the project
      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key from GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_PRIVATE_KEY" > ~/.ssh/TreeTrack-vm-key
          chmod 600 ~/.ssh/TreeTrack-vm-key

      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/TreeTrack-vm-key TreeTrack@4.222.232.148 'bash deploy.sh'
