name: Build TreeTrack App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java and Android SDK
      - name: Set up Java and Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      # Step 3: Build the Android app using Gradle
      - name: Build the app
        run: |
          cd your-app-directory
          ./gradlew assembleRelease

      # Step 4: Upload APK to GitHub Releases (optional)
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
