name: Build and Deploy TreeTrack App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java JDK and Android SDK
      - name: Set up Java and Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install openjdk-11-jdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          echo "y" | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      # Step 3: Build the Android app using Gradle
      - name: Build the app
        run: |
          cd your-app-directory
          ./gradlew assembleRelease

      # Step 4: Upload the APK (optional, for distribution)
      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk

      # Step 5: Deploy Firebase Functions (if using Firebase)
      - name: Deploy Firebase Functions
        run: |
          curl -sL https://firebase.tools | bash
          firebase deploy --only functions --token $FIREBASE_TOKEN

      # Step 6: Set up SSH key for Azure VM deployment
      - name: Set up SSH key from GitHub Secrets
        run: |
          mkdir -p ~/.ssh
          echo "$AZURE_SSH_PRIVATE_KEY" > ~/.ssh/TreeTrack-vm-key
          chmod 600 ~/.ssh/TreeTrack-vm-key

      # Step 7: Connect to Azure VM and run the deployment script
      - name: Deploy to Azure VM
        run: |
          ssh -i ~/.ssh/TreeTrack-vm-key TreeTrack@4.222.232.148 'bash -s' < ./deploy.sh
